# Generated by Django 3.2.8 on 2021-11-03 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211102_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 12, 34, 16, 808240)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 12, 34, 16, 808240)),
        ),
    ]
