# Generated by Django 3.2.8 on 2021-10-24 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 14, 18, 18, 9618, tzinfo=utc))),
                ('is_deleted', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='books\\picture')),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Historical', 'Historical'), ('Scientific', 'Scientific'), ('Romance', 'Romance'), ('ForKids', 'For Kids'), ('Literature', 'Literature')], max_length=200)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kartoteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 14, 18, 18, 9618, tzinfo=utc))),
                ('is_deleted', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('return_date', models.DateTimeField(default=datetime.datetime(2021, 11, 8, 14, 18, 18, 14642, tzinfo=utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
