# Generated by Django 3.2.8 on 2021-10-24 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211024_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 28, 41, 883522)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 28, 41, 883522)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 19, 28, 41, 887523)),
        ),
    ]
