# Generated by Django 3.2.8 on 2021-10-31 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20211024_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 5, 58, 936592)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 5, 58, 936592)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 13, 5, 58, 939593)),
        ),
    ]
