# Generated by Django 3.2.8 on 2021-11-03 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211102_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 12, 34, 16, 808240)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 12, 34, 16, 808240)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 12, 34, 16, 811241)),
        ),
    ]
