# Generated by Django 3.2.8 on 2021-11-14 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20211114_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 17, 0, 47, 978708)),
        ),
    ]
