# Generated by Django 3.2.8 on 2021-12-01 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_kartoteka_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default=None, upload_to='books\\file'),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 10, 46, 27, 219004)),
        ),
    ]
