# Generated by Django 3.2.8 on 2021-12-01 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20211201_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartoteka',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 10, 48, 53, 644594)),
        ),
    ]
